# format 3.x, validated on W10 - there is no "mode/uid/gid" for docker-compose 1.29/W10
# you should provide your private/public RSA key in ./ssh dir (named id_rsa.mpi/id_rsa.mpi.pub)
# docker swarm init, then you have to do // note version_mpinet is the name of the overlay
# docker network create --driver=overlay --attachable yml_mpinet
#
# Feb, 08, 2024 - Jean-Michel Batto

version: "3.9"

services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: slurm_acct_db
      MARIADB_USER: slurm
      MARIADB_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mpinet

  slurmdbd:
    image: jmbatto/m2chps-slurm-cluster:latest
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
    shm_size: '512m'
    networks:
      - mpinet

  slurmctld:
    image: jmbatto/m2chps-slurm-cluster:latest
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
    shm_size: '512m'
    networks:
      - mpinet

  c1:
    image: jmbatto/m2chps-slurm-cluster:latest
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    shm_size: '512m'
    networks:
      - mpinet
  c2:
    image: jmbatto/m2chps-slurm-cluster:latest
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    shm_size: '512m'
    networks:
      - mpinet
      
networks:
  mpinet:
    external: true
    name : yml_mpinet
    driver: overlay
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
